from django.urls import path
from django.conf.urls import url
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    ### PAGE
    path('', views.first_page, name='first_page'),
    path('index/', views.index, name='index'),
    path('transaction/<str:orderoprno>', views.transaction, name='transaction'),
    path('join_activity/<str:orderoprno>', views.join_activity, name='join_activity'),
    path('lot_traveller/<str:orderno>&<str:lotno>', views.lot_traveller, name='lot_traveller'),
    path('ab_graph_mn/<str:frt>&<str:fdate>', views.ab_graph_mn, name='ab_graph_mn'),
    path('tool_store/', views.tool_store, name='tool_store'),
    #-- MASTER
    path('master/wc/', views.master_wc, name='master_wc'),
    path('master/emp/', views.master_emp, name='master_emp'),
    path('master/rej/', views.master_rej, name='master_rej'),
    path('master/matg/', views.master_matg, name='master_matg'),
    path('master/purg/', views.master_purg, name='master_purg'),
    path('master/curr/', views.master_curr, name='master_curr'),
    path('master/tool/', views.master_tool, name='master_tool'),
    path('master/ctt/', views.master_ctt, name='master_ctt'),
    #-- DATA PAGE
    path('wc/<str:wcno>&<str:fmonth>', views.wc, name='wc'),
    path('emp/<str:empid>&<str:fmonth>', views.emp, name='emp'),
    #-- MONITORING
    path('monitoring/working_order/', views.working_order, name='working_order'),
    path('monitoring/working_wc/', views.working_wc, name='working_wc'),
    path('monitoring/working_emp/', views.working_emp, name='working_emp'),
    path('monitoring/delay_operation/<str:fwc>', views.delay_operation, name='delay_operation'),
    path('monitoring/none_working_wc/', views.none_working_wc, name='none_working_wc'),
    path('monitoring/none_start_order/', views.none_start_order, name='none_start_order'),
    path('monitoring/pending_pln_fai/', views.pending_pln_fai, name='pending_pln_fai'),
    #-- REPORT
    path('report/ot_table/<str:fmonth>', views.ot_table, name='ot_table'),
    path('report/mp_ot_auto_machine/<str:fmonth>', views.mp_ot_auto_machine, name='mp_ot_auto_machine'),
    path('report/oper_no_time/<str:fmonth>', views.oper_no_time, name='oper_no_time'),
    path('report/emp_work_time/<str:fstartdate>&<str:fstopdate>&<str:emp_type>', views.emp_work_time, name='emp_work_time'),
    path('report/closed_prod/completed_order/<str:ftype>&<str:fdate>&<str:fmonth>&<str:fstartdate>&<str:fstopdate>', views.completed_order, name='completed_order'),
    path('report/closed_prod/rejected_order/<str:ftype>&<str:fdate>&<str:fmonth>&<str:fstartdate>&<str:fstopdate>', views.rejected_order, name='rejected_order'),
    path('report/closed_prod/canceled_order/<str:ftype>&<str:fdate>&<str:fmonth>&<str:fstartdate>&<str:fstopdate>', views.canceled_order, name='canceled_order'),
    path('report/work_records/<str:ftype>&<str:fdate>&<str:fmonth>&<str:fstartdate>&<str:fstopdate>', views.work_records, name='work_records'),
    path('report/con_operation/<str:fwc>&<str:fmonth>', views.con_operation, name='con_operation'),
    path('report/operating_history/<str:fwc>&<str:fmc>&<str:ftype>&<str:fstartdate>&<str:fstopdate>&<str:fmonth>', views.operating_history, name='operating_history'),
    path('report/over_est_operation/<str:fwc>&<str:fweek>', views.over_est_operation, name='over_est_operation'),
    path('report/plan_act_cycle_time/<str:ffgcode>&<str:fwc>&<str:ftype>&<str:fstartdate>&<str:fstopdate>&<str:fmonth>', views.plan_act_cycle_time, name='plan_act_cycle_time'),
    path('report/order_analysis/', views.order_analysis, name='order_analysis'),
    #-- REPORT/GRAPH
    path('report/graph/ab_graph/ab_graph_wcg/<str:fwcg>&<str:ftype>&<str:fmonth>&<str:fyear>', views.ab_graph_wcg, name='ab_graph_wcg'),
    path('report/graph/ab_graph/ab_graph_rt/<str:frt>&<str:ftype>&<str:fmonth>&<str:fyear>', views.ab_graph_rt, name='ab_graph_rt'),
    path('report/graph/reject_per/reject_per_pfc/<str:fpfc>&<str:fmonth>', views.reject_per_pfc, name='reject_per_pfc'),
    path('report/graph/reject_per/reject_per_wcg/<str:fwcg>&<str:fmonth>', views.reject_per_wcg, name='reject_per_wcg'),
    path('report/graph/reject_per/reject_per_rt/<str:fwc>&<str:fmonth>', views.reject_per_rt, name='reject_per_rt'),
    path('report/graph/efficiency/efficiency_pfc/<str:fpfc>&<str:fmonth>', views.efficiency_pfc, name='efficiency_pfc'),
    path('report/graph/efficiency/efficiency_wcg/<str:fwcg>&<str:fmonth>', views.efficiency_wcg, name='efficiency_wcg'),
    path('report/graph/efficiency/efficiency_wc/<str:fwc>&<str:fmonth>', views.efficiency_wc, name='efficiency_wc'),
    path('report/graph/reject_per/reject_rc_pfc/<str:fpfc>&<str:fmonth>', views.reject_rc_pfc, name='reject_rc_pfc'),
    path('report/graph/cumulative_rejection/', views.cumulative_rejection, name='cumulative_rejection'),
    path('report/graph/cumulative_rejection_record/', views.cumulative_rejection_record, name='cumulative_rejection_record'),
    #-- SAP
    path('sap_log/data_from_sap/sap_order/<str:fdate>&<str:fhour>', views.sap_order, name='sap_order'),
    path('sap_log/data_from_sap/sap_routing/<str:fdate>&<str:fhour>', views.sap_routing, name='sap_routing'),
    path('sap_log/data_from_sap/sap_component/<str:fdate>&<str:fhour>', views.sap_component, name='sap_component'),
    path('sap_log/data_to_sap/sap_report/<str:fdate>&<str:fhour>', views.sap_report, name='sap_report'),
    path('sap_log/data_to_sap/sap_mod/<str:fdate>&<str:fhour>', views.sap_mod, name='sap_mod'),
    path('blank/', views.blank, name='blank'),
    #-- ADMIN PANEL
    path('admin_panel/controller/', views.controller, name='controller'),
    path('admin_panel/error_data/', views.error_data, name='error_data'),
    ### REQUEST
    path('fp_emp_search/', views.fp_emp_search, name='fp_emp_search'),
    #-- MAIN TABLE
    path('get_workcenter_data/', views.get_workcenter_data, name='get_workcenter_data'),
    path('get_operator_data/', views.get_operator_data, name='get_operator_data'),
    #-- INNER MAIN TABLE
    path('get_operating_workcenter_list/', views.get_operating_workcenter_list, name='get_operating_workcenter_list'),
    path('get_operating_operator_list/', views.get_operating_operator_list, name='get_operating_operator_list'),
    path('add_operating_workcenter/', views.add_operating_workcenter, name='add_operating_workcenter'),
    path('delete_operating_workcenter/', views.delete_operating_workcenter, name='delete_operating_workcenter'),
    path('idle_operating_workcenter/', views.idle_operating_workcenter, name='idle_operating_workcenter'),
    path('stop_idle_operating_workcenter/', views.stop_idle_operating_workcenter, name='stop_idle_operating_workcenter'),
    path('stop_operating_workcenter/', views.stop_operating_workcenter, name='stop_operating_workcenter'),
    path('add_operating_operator/', views.add_operating_operator, name='add_operating_operator'),
    path('start_work_operating_operator/', views.start_work_operating_operator, name='start_work_operating_operator'),
    path('stop_setup_operating_operator/', views.stop_setup_operating_operator, name='stop_setup_operating_operator'),
    path('stop_work_operating_operator/', views.stop_work_operating_operator, name='stop_work_operating_operator'),
    #-- CONFIRM & MANUAL REPORT & FIX OVERTIME
    path('get_data_for_confirm/', views.get_data_for_confirm, name='get_data_for_confirm'),
    path('confirm/', views.confirm, name='confirm'),
    path('manual_report/', views.manual_report, name='manual_report'),
    path('fix_overtime/', views.fix_overtime, name='fix_overtime'),
    #-- JOIN
    path('join/', views.join, name='join'),
    path('break_join/', views.break_join, name='break_join'),
    #-- MODIFIER
    path('inc_qty/', views.inc_qty, name='inc_qty'),
    path('dec_qty/', views.dec_qty, name='dec_qty'),
    path('delete_operation/', views.delete_operation, name='delete_operation'),
    path('add_operation/', views.add_operation, name='add_operation'),
    path('change_operation/', views.change_operation, name='change_operation'),
    #-- NOTE
    path('save_note/', views.save_note, name='save_note'),
    path('save_over_est_note/', views.save_over_est_note, name='save_over_est_note'),
    #-- VALIDATION
    path('validate_new_operation/', views.validate_new_operation, name='validate_new_operation'),
    path('validate_routing/', views.validate_routing, name='validate_routing'),
    path('validate_work_center/', views.validate_work_center, name='validate_work_center'),
    path('validate_operator/', views.validate_operator, name='validate_operator'),
    path('validate_password/', views.validate_password, name='validate_password'),
    path('validate_section_chief_password/', views.validate_section_chief_password, name='validate_section_chief_password'),
    path('validate_admin_password/', views.validate_admin_password, name='validate_admin_password'),
    path('validate_super_admin_password/', views.validate_super_admin_password, name='validate_super_admin_password'),
    path('validate_new_user_id/', views.validate_new_user_id, name='validate_new_user_id'),
    path('validate_new_password/', views.validate_new_password, name='validate_new_password'),
    path('validate_wc_no/', views.validate_wc_no, name='validate_wc_no'),
    path('validate_upload_tool_list/', views.validate_upload_tool_list, name='validate_upload_tool_list'),
    path('validate_transfer_tool/', views.validate_transfer_tool, name='validate_transfer_tool'),
    path('validate_change_tool_wc/', views.validate_change_tool_wc, name='validate_change_tool_wc'),
    path('validate_add_new_tool/', views.validate_add_new_tool, name='validate_add_new_tool'),
    #-- ETC
    path('increase_lot_no/', views.increase_lot_no, name='increase_lot_no'),
    path('fix_rm_mat_code/', views.fix_rm_mat_code, name='fix_rm_mat_code'),
    path('set_wc_target/', views.set_wc_target, name='set_wc_target'),
    path('set_wc_cap/', views.set_wc_cap, name='set_wc_cap'),
    path('clear_pln_fai/', views.clear_pln_fai, name='clear_pln_fai'),
    path('remark_pln_fai/', views.remark_pln_fai, name='remark_pln_fai'),
    path('save_abgraph_mn/', views.save_abgraph_mn, name='save_abgraph_mn'),
    path('get_wcs_of_profit_center/', views.get_wcs_of_profit_center, name='get_wcs_of_profit_center'),
    path('generate_order_analysis/', views.generate_order_analysis, name='generate_order_analysis'),
    #-- TOOL LIST
    path('upload_tool_list_save/', views.upload_tool_list_save, name='upload_tool_list_save'),
    path('transfer_tool/', views.transfer_tool, name='transfer_tool'),
    path('return_tool_all/', views.return_tool_all, name='return_tool_all'),
    path('return_tool/', views.return_tool, name='return_tool'),
    path('change_tool/', views.change_tool, name='change_tool'),
    path('change_tool_wc/', views.change_tool_wc, name='change_tool_wc'),
    path('add_new_tool/', views.add_new_tool, name='add_new_tool'),
    ## ADMIN PANEL
    path('add_new_user/', views.add_new_user, name='add_new_user'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('change_user_password/', views.change_user_password, name='change_user_password'),
    path('mpa/', views.mpa, name='mpa'),
    path('add_wc/', views.add_wc, name='add_wc'),
    # path('reset_all/', views.reset_all, name='reset_all'),
    path('reset_order/', views.reset_order, name='reset_order'),
    path('cancel_order/', views.cancel_order, name='cancel_order'),
    path('sqty_operation/', views.sqty_operation, name='sqty_operation'),
    path('drawing/<str:dir>&<str:fg_code>', views.drawing, name='drawing'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    # DISKPULSE
    path('diskpulse/', views.diskpulse, name='diskpulse'),
    path('diskpulse_search/', views.diskpulse_search, name='diskpulse_search'),
]+ static(settings.MEDIA_URL, serve, document_root=settings.MEDIA_ROOT)
